# Dependencies
markdown            : kramdown
redcarpet:
  extensions        : ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]
highlighter         : rouge
gems                : ["jekyll-paginate", "jekyll-assets"]

# Permalinks
permalink           : pretty

# Setup
title               : TIna雜記
tagline             : ''
description         : 'Android開發記錄,雜七雜八紀錄'
baseurl             : /

author              : Yi Ting Huang
name                : 'Yi Ting Huang'
url                 :  https://t79111222.github.io/

paginate            : 5

# Custom vars
version             : 0.1.0
github_username     : t79111222
